/*CREATE TABLE Std
(
 S_NO CHAR(7) PRIMARY KEY(S_NO),
 NAME CHAR(10),
 AGE SMALLINT CHECK(AGE BETWEEN 15 AND 20)
)*/

/**/
CREATE TABLE S_C_Info
(
 St_ID CHAR(10) NOT NULL,
 
 C_NO CHAR(10) NOT NULL,
 Score INT NULL,
 PRIMARY KEY(St_ID,C_NO),
 FOREIGN KEY(St_ID)REFERENCES St_Info(St_ID),
 FOREIGN KEY(C_NO)REFERENCES C_Info(C_NO)
)